language: perl
perl:
  - "5.36"
  - "5.24"
  - "5.20"
  - "5.14"
  - "5.8"
  - "5.6"
cache:
  directories:
    - $HOME/perl5
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
